---
name: CI Arm64

on: # yamllint disable-line rule:truthy
  workflow_dispatch:

env:
  ACR_IMAGE_PATH_FRONTEND: ${{ secrets.ACR_LOGIN_SERVER }}/frontendmodule:1.0.${{ github.run_number }}-arm32v7
  ACR_IMAGE_PATH_BACKEND: ${{ secrets.ACR_LOGIN_SERVER }}/backendmodule:1.0.${{ github.run_number }}-arm32v7

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          make install

      - name: Install qemu emulator
        run: |
          make install_qemu

      - name: Build backend docker image
        run: |
          cd ./EdgeSolution/modules/BackendModule
          docker buildx build --platform linux/arm/v7 -t ${{env.ACR_IMAGE_PATH_BACKEND}} -f Dockerfile.arm32v7 .

      # - name: Push backend docker image
      #   run: |
      #     docker push ${{env.ACR_IMAGE_PATH_BACKEND}}
